### ISSUE TITLE
[BUG] Binary sensor has wrong availability message

### ISSUE THREAD

**Issue by mion00** [unixorn/ha-mqtt-discovery#10]
**Describe the bug**
When creating a binary sensor, the _availability_ topic is currently hard-coded to the _state_ topic.

According to the [docs](https://www.home-assistant.io/integrations/binary_sensor.mqtt/#availability) however the availability payload expects an `online` or `offline` message by default, so using `ON` and `OFF` state confuses HA.

**To Reproduce**
The following example code creates a binary sensor, then toggles its state.
```python
mysensor = BinarySensor(settings={
    "mqtt_server": "localhost",
    "client_name": "client",
    "mqtt_user": "user",
    "mqtt_password": "password",
    "mqtt_prefix": "homeassistant",

    "metric_name": "sensor",
    "device_id": "test_device",
    "unique_id": "my_sensor",
    "device_name": "MySensor",
    "device_class": "motion",
})
mysensor.on()
await asyncio.sleep(5)
mysensor.off()
await asyncio.sleep(5)
mysensor.on()
```
**Expected behavior**
At the end of the script the sensor should appear `on`, instead it appears `unavailable`.

**Screenshots**
![Screenshot from 2023-02-12 08-56-26](https://user-images.githubusercontent.com/4510647/218299732-a4c945bf-99a7-4dd5-844b-df9b6be7b612.png)

After manually publishing a MQTT message to the availability topic `homeassistant/binary_sensor/MySensor/state` with content  `online`:
![Screenshot from 2023-02-12 09-03-58](https://user-images.githubusercontent.com/4510647/218299823-95c95166-12ee-4354-aca3-630f426fd25c.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 Cinammon
 - Browser Google Chrome
 - Version 109.0.5414.74

**Comment by unixorn** [comment]
Deferring until after #15 is merged

**Comment by unixorn** [comment]
Sounds good to me.
