### ISSUE TITLE
Use official python docker image

### ISSUE THREAD

**Issue by mion00** [unixorn/ha-mqtt-discovery#23]
**Is your feature request related to a problem? Please describe.**
Is there a specific reason why the Dockerfile is based on `unixorn/debian-py3`?
Isn't it more straightforward to use the official [python](https://hub.docker.com/_/python) image? That way any security update or issue to the base OS are handled directly in the official image, and we have one less thing to worry about.

**Describe the solution you'd like**
Use `FROM python:<what version should we use?>` in the Dockerfile.

**Describe alternatives you've considered**
Maybe use their alpine variant to gain an even smaller footprint?

**Comment by unixorn** [comment]
I'm fine with moving to the official Python image. I'd prefer avoiding the alpine variant because in the past I've seen issues when using modules with C extensions, especially when building multi-architecture images like `make fatimages` does.

**Comment by mion00** [comment]
Understood, let's keep the standard Debian-based Python image then.
I saw the `fatimage` target and I imagine you run this locally to publish the new versions.
Have you considered automating the build and release with the [official Github Action by Docker](https://github.com/marketplace/actions/build-and-push-docker-images)? It can even build for multiple architectures!
We could setup a complete pipeline that starting from a Git tag could publish to both PyPI and Docker Hub automatically.
