### ISSUE TITLE
Create authentication secrets for PyPi and Docker Hub

### ISSUE THREAD

**Issue by unixorn** [unixorn/ha-mqtt-discovery#40]
Per #38, automating new version publishing requires us to

- define Github secrets PYPI_USERNAME and PYPI_PASSWORD to access PyPI
- define Docker Hub authentication to publish to it
- Create an automation account on PyPi
- Create an automation account on Docker Hub - maybe `ha-mqtt-tooling`?

**Comment by mion00** [comment]
Here is some information for Poetry: https://github.com/python-poetry/poetry/issues/5285#issuecomment-1336177595

**Comment by mion00** [comment]
Are you using the PyPI API token?
From the error logs it seems we need to set username to `__token__` in that case:
https://github.com/unixorn/ha-mqtt-discovery/actions/runs/4255018739/jobs/7402077497#step:7:1

**Comment by unixorn** [comment]
Added a `PYPI_PASSWORD` secret scoped to this module.
